/**
 * Default configuration registry for applications and demo windows.
 */
export const demoAppConfigs = {
  terminal: {
    id: 'terminal',
    appId: 'terminal',
    title: 'Terminal — zsh',
    defaultSize: { width: 680, height: 440 },
    minSize: { width: 420, height: 260 },
    description: 'Interactive command-line interface environment coming in Phase 4.',
    badge: 'Terminal Shell',
    theme: 'dark',
  },
  finder: {
    id: 'finder',
    appId: 'finder',
    title: 'Finder',
    defaultSize: { width: 780, height: 500 },
    minSize: { width: 480, height: 300 },
    description: 'File system explorer and portfolio project navigator coming in Phase 4.',
    badge: 'File Manager',
    theme: 'light',
  },
  github: {
    id: 'github',
    appId: 'github',
    title: 'GitHub Repositories',
    defaultSize: { width: 840, height: 520 },
    minSize: { width: 500, height: 320 },
    description: 'Showcase of open-source projects, contributions, and repositories.',
    badge: 'Open Source',
    theme: 'dark',
  },
  linkedin: {
    id: 'linkedin',
    appId: 'linkedin',
    title: 'LinkedIn Profile',
    defaultSize: { width: 800, height: 520 },
    minSize: { width: 480, height: 320 },
    description: 'Professional experience, networking, and career history.',
    badge: 'Social & Career',
    theme: 'light',
  },
  safari: {
    id: 'safari',
    appId: 'safari',
    title: 'Gallery',
    defaultSize: { width: 920, height: 600 },
    minSize: { width: 520, height: 380 },
    description: 'Personal image gallery — drop photos into src/assets/gallery.',
    badge: 'Image Gallery',
    theme: 'dark',
  },
  projects: {
    id: 'projects',
    appId: 'projects',
    title: 'Projects Showcase',
    defaultSize: { width: 820, height: 520 },
    minSize: { width: 480, height: 300 },
    description: 'Curated gallery of featured engineering and design projects.',
    badge: 'Portfolio Works',
    theme: 'dark',
  },
  resume: {
    id: 'resume',
    appId: 'resume',
    title: 'Resume / CV',
    defaultSize: { width: 720, height: 560 },
    minSize: { width: 440, height: 340 },
    description: 'Interactive resume with printable format and downloadable PDF.',
    badge: 'Curriculum Vitae',
    theme: 'light',
  },
  about: {
    id: 'about',
    appId: 'about',
    title: 'About Chirrayu',
    defaultSize: { width: 620, height: 420 },
    minSize: { width: 400, height: 260 },
    description: 'Biography, technical skill-set, passions, and background overview.',
    badge: 'System Profile',
    theme: 'dark',
  },
  settings: {
    id: 'settings',
    appId: 'settings',
    title: 'System Settings',
    defaultSize: { width: 700, height: 480 },
    minSize: { width: 460, height: 300 },
    description: 'Desktop preferences, theme customizations, wallpaper selector, and sound toggles.',
    badge: 'Preferences',
    theme: 'light',
  },
  trash: {
    id: 'trash',
    appId: 'trash',
    title: 'Trash',
    defaultSize: { width: 560, height: 360 },
    minSize: { width: 380, height: 240 },
    description: 'Recycle bin and discarded items archive.',
    badge: 'Bin',
    theme: 'light',
  },
};
